/**
 * generate-github-stats.ts
 *
 * Queries the GitHub GraphQL API and generates aggregated profile stats.
 * Writes output to assets/github-impact.md (safe for public repos).
 *
 * Usage:
 *   GITHUB_TOKEN=your_token npx tsx scripts/generate-github-stats.ts
 *
 * Required secret: PROFILE_STATS_TOKEN (read:user scope)
 * Private repository names are never exposed in the output.
 */

import { writeFileSync, mkdirSync } from "fs";

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const USERNAME = "PauloHSOliveira";

if (!GITHUB_TOKEN) {
  console.warn(
    "[warn] GITHUB_TOKEN is not set. Skipping stats generation."
  );
  process.exit(0);
}

const GRAPHQL_ENDPOINT = "https://api.github.com/graphql";

interface ContributionStats {
  totalCommitContributions: number;
  totalPullRequestContributions: number;
  totalPullRequestReviewContributions: number;
  totalIssueContributions: number;
  totalRepositoriesWithContributedCommits: number;
}

async function query(q: string): Promise<unknown> {
  const res = await fetch(GRAPHQL_ENDPOINT, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query: q }),
  });

  if (!res.ok) {
    throw new Error(`GitHub API error: ${res.status} ${res.statusText}`);
  }

  return res.json();
}

async function fetchStats(): Promise<ContributionStats> {
  const currentYear = new Date().getFullYear();
  const from = `${currentYear - 1}-01-01T00:00:00Z`;
  const to = new Date().toISOString();

  const q = `
    {
      user(login: "${USERNAME}") {
        contributionsCollection(from: "${from}", to: "${to}") {
          totalCommitContributions
          totalPullRequestContributions
          totalPullRequestReviewContributions
          totalIssueContributions
          totalRepositoriesWithContributedCommits
        }
      }
    }
  `;

  const data = (await query(q)) as {
    data: {
      user: {
        contributionsCollection: ContributionStats;
      };
    };
  };

  return data.data.user.contributionsCollection;
}

async function main() {
  try {
    console.log("[info] Fetching GitHub stats...");
    const stats = await fetchStats();

    const output = [
      `<!-- Auto-generated by scripts/generate-github-stats.ts -->`,
      `<!-- Last updated: ${new Date().toISOString()} -->`,
      ``,
      `## Recent Activity (Last 12 Months)`,
      ``,
      `| Metric | Count |`,
      `|--------|-------|`,
      `| Commits | ${stats.totalCommitContributions}+ |`,
      `| Pull Requests | ${stats.totalPullRequestContributions}+ |`,
      `| Code Reviews | ${stats.totalPullRequestReviewContributions}+ |`,
      `| Issues | ${stats.totalIssueContributions}+ |`,
      `| Repositories contributed to | ${stats.totalRepositoriesWithContributedCommits}+ |`,
      ``,
      `> Includes contributions from private repositories. Repository names are not disclosed.`,
    ].join("\n");

    mkdirSync("assets", { recursive: true });
    writeFileSync("assets/github-impact.md", output, "utf-8");

    console.log("[info] Stats written to assets/github-impact.md");
  } catch (err) {
    console.error("[error] Failed to generate stats:", err);
    // Fail gracefully — do not block the workflow
    process.exit(0);
  }
}

main();
